import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/home/enjalot/.cache/ms-playwright/chromium-1223/chrome-linux64/chrome',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('bl-type-v1')));
const pins=async()=>(await saved()).pins;
await page.goto(process.env.BASE_URL||'http://gsv.local:5186');await page.waitForSelector('#style-map');
await expect(page.locator('#undo-use')).toBeDisabled();await expect(page.locator('#redo-use')).toBeDisabled();
await page.locator('#style-map').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');
await expect(page.locator('.nearest-mini')).toHaveCount(26,{timeout:30000});await expect(page.locator('#use-nearest-reference')).toBeEnabled();
assert.deepEqual(await pins(),{});assert.equal((await saved()).selectionHistory.past.length,0,'Inspection must not consume undo');
const expected=await page.locator('.nearest-mini').evaluateAll(tiles=>Object.fromEntries(tiles.map(t=>[t.querySelector('b').firstChild.textContent,t.querySelector('img').getAttribute('src').match(/(\d+)\.webp/)[1]])));
const mini=page.locator('.nearest-mini:not(.is-reference)').first();const index=await mini.getAttribute('data-neighbor-index');await mini.hover();await expect(mini).toHaveClass(/hovered/);await expect(page.locator('#style-map')).toHaveAttribute('data-hover-index',index);
const bluePixels=await page.locator('#style-map').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let n=0;for(let i=0;i<d.length;i+=4)if(d[i]<15&&Math.abs(d[i+1]-124)<10&&Math.abs(d[i+2]-170)<10)n++;return n;});assert(bluePixels>20,'Hovered point is blue on canvas');
await page.locator('#style-map').scrollIntoViewIfNeeded();
const pointPosition=await page.evaluate(async ({index,mapUrl})=>{const m=await(await fetch(mapUrl)).json(),c=document.querySelector('#style-map'),r=c.getBoundingClientRect(),xy=m.coords.centered,xs=xy.map(p=>p[0]),ys=xy.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),scale=Math.min((r.width-60)/(maxX-minX),(r.height-60)/(maxY-minY));return {x:r.left+(xy[index][0]-(minX+maxX)/2)*scale+r.width/2,y:r.top+(xy[index][1]-(minY+maxY)/2)*scale+r.height/2};},{index:Number(index),mapUrl:(process.env.ASSET_ORIGIN||'')+'/data/style-map.json'});
await page.mouse.move(pointPosition.x,pointPosition.y);await expect(page.locator('#style-map')).toHaveAttribute('data-hover-index',index);await expect(mini).toHaveClass(/hovered/);await expect(page.locator('#map-tooltip')).toBeVisible();

await page.locator('.map-layout').screenshot({path:'artifacts/nearest-map-highlight.png'});await page.locator('#nearest-strip').screenshot({path:'artifacts/nearest-miniatures.png'});
await page.locator('.candidate').first().click();await page.locator('#use-tile').click();const first=await pins();assert.equal(Object.keys(first).length,1);assert.notEqual(first.A,expected.A);
await page.locator('[data-mini-use]').nth(1).click();const second=await pins();assert.equal(Object.keys(second).length,2);
await page.locator('#undo-use').click();assert.deepEqual(await pins(),first);await page.locator('#undo-use').click();assert.deepEqual(await pins(),{});
await page.locator('#redo-use').click();assert.deepEqual(await pins(),first);await page.locator('#redo-use').click();assert.deepEqual(await pins(),second);
await page.locator('#use-nearest-reference').click();assert.deepEqual(await pins(),expected,'Nearest alphabet replaces existing letter assignments');
const length=(await saved()).selectionHistory.past.length;await page.locator('#assign-nearest').click();assert.equal((await saved()).selectionHistory.past.length,length,'No-op bulk use must not add an undo step');
await page.locator('#undo-use').click();assert.deepEqual(await pins(),second,'Bulk assignment is one undo step');await page.locator('#redo-use').click();assert.deepEqual(await pins(),expected);
await page.locator('#style-map').focus();await page.keyboard.press('Control+z');assert.deepEqual(await pins(),second);await page.keyboard.press('Control+Shift+z');assert.deepEqual(await pins(),expected);
await page.locator('#sentence').fill('native');await page.locator('#sentence').press('End');await page.keyboard.type(' typing');await page.keyboard.press('Control+z');assert.notEqual(await page.locator('#sentence').inputValue(),'native typing','Native text undo must still work');assert.deepEqual(await pins(),expected,'Typing undo must not alter glyph choices');
await page.locator('#undo-use').click();await page.reload();await page.waitForSelector('#style-map');assert.deepEqual(await pins(),second);await expect(page.locator('#redo-use')).toBeEnabled();await page.locator('#redo-use').click();assert.deepEqual(await pins(),expected,'Redo stack survives reload');
await page.locator('#undo-use').click();await page.locator('#unlock-all').click();assert.deepEqual(await pins(),{});await expect(page.locator('#redo-use')).toBeDisabled();await page.locator('#undo-use').click();assert.deepEqual(await pins(),second,'Unpin-all participates in history');
await page.locator('#letter-picker').selectOption('A');const beforeHide=await saved();await page.locator('#hide-tile').click();assert((await saved()).hidden.length>beforeHide.hidden.length);await page.locator('#undo-use').click();assert.deepEqual((await saved()).hidden,beforeHide.hidden);assert.deepEqual(await pins(),beforeHide.pins);
const beforeShuffle=await saved();await page.locator('#shuffle').click();assert.notEqual((await saved()).seed,beforeShuffle.seed);await page.locator('#undo-use').click();assert.equal((await saved()).seed,beforeShuffle.seed);
await page.locator('#style-map').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await expect(page.locator('.nearest-mini')).toHaveCount(26);
await page.setViewportSize({width:390,height:844});await page.locator('#nearest-strip').scrollIntoViewIfNeeded();await page.locator('#nearest-strip').screenshot({path:'artifacts/nearest-miniatures-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);console.log('PASS: nearest alphabet replacement, miniature previews and blue linked hover, atomic multi-step undo/redo, no-op handling, persistence, branching, keyboard/native text undo, hiding, unpinning, shuffling, mobile.');await browser.close();
